name:                codalang
version:             0.1.0.0
github:              jyh1/codalang
license:             BSD3
author:              Yonghao Jin
maintainer:          yonghao.jyh1@gmail.com
copyright:           2019 Yonghao Jin

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/codalang#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.8.0
- lens
- typed-process
- mtl
- trifecta
- parsers
- prettyprinter
- wreq
- aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  codalang-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - codalang
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  codalang-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - codalang
    - hspec
    - QuickCheck

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
